# SITE CONFIGURATION
title: Mike G. Lopez # your site title
author: mikeglopez # You :P
description: > # Meta description of Homepage
  A blog about JavaScript and more
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikeglopez.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Mike G. Lopez
  links:
    - https://twitter.com/MIKEGL0PEZ
    - https://www.linkedin.com/in/mikeglopez/
    - https://github.com/mikeglopez

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Portfolio', link: '/portfolio'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  I'm a software engineer based in Chicago, IL. I love watching my ideas come to life.

hero_img: posts/lake_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: mikeglopez@me.com # email for form submission

twitter_username: MIKEGL0PEZ # replace with your_twitter_username or comment to remove link from footer
github_username:  mikeglopez # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
google_tag_manager: UA-141480877-1

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
